### ISSUE TITLE
Display STDOUT from SSH immediately

### ISSUE THREAD

**Issue by dploeger** [JetBrains/teamcity-deployer-plugin#74]
We're using the SSH Exec Runner for remote deployment tasks. Currently, the Output of the deployment tasks is only written to the TeamCity log on completion of the command.

This leaves us blind for the duration of the - sometimes long running - task.

Please write the output immediately into the TeamCity log.

**Comment by STeveShary** [comment]
+1

I checked to see if the output would be immediately available using the "##teamcity[ message '...' ]" format but it seems to have no effect.  Output is put on the build log when the script is finished.

I'd like to also add that this issue encourages teams to put their ssh commands directly into teamcity rather than using a shell script.  I think that it is a better practice to keep all of the exec commands in a shell script in with the source code.  This practice allows teams to move the execs through different environments and allows the team to better track which changes cause a change in the CI pipeline.  I am a fan of infrastructure as source code.

**Comment by nskvortsov** [comment]
implemented
